# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: nodejs:16

# The configuration of app when it is exposed to the web.
web:
  commands:
   start: "node app.js"

# The size of the persistent disk of the application (in MB).
disk: 512

mounts:
    'run':
        source: local
        source_path: run